name: build 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build: 
    name: build-linux
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: tipi builds project 
        run: |
          export HOME=/root
          tipi . -t linux-cxx17 --verbose